out_message: "i don't get it"

steps:
  - id: 'start'
    type: send
    respond_to: null
    text: null
    file_id: AgACAgIAAxkBAAMFZ5QXvpkuUZFWSzLQpJ9YwdTROXMAAi_nMRvoYaFIva7gZEOYkNEBAAMCAAN5AAM2BA
    keyboard: ['good morning']
    after: set_next_step
  - id: 'teeth'
    type: send
    respond_to: null
    text: null
    sticker_id: CAACAgIAAxkBAAOMZ5VdpsBPVVp0co4oR6wV5e-IIIgAAgEAA8A2TxMYLnMwqz8tUTYE
    keyboard: ['good morning']
    after: set_next_step
  - id: 'intro'
    type: send
    respond_to: null
    text: 'bebraaa'
    file_id: null
    keyboard: ['good morning']
    after: set_next_step
  - id: 'intro_2'
    type: send
    respond_to: null
    text: 'r u redy'
    file_id: null
    keyboard: ['i am ready!']
    after: set_next_step
  - id: 'task_1_1'
    type: send
    respond_to: null
    text: 'washmash'
    file_id: null
    keyboard: null
    after: set_next_step
  - id: 'task_1_2'
    type: send
    respond_to: '/start bebra'
    text: 'washmash'
    file_id: null
    keyboard: null
    after: null